//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lemaf.Services.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lemaf.Services.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Capacidade de pessoas informada está incorreta..
        /// </summary>
        public static string ErroCapacidade {
            get {
                return ResourceManager.GetString("ErroCapacidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Codigo da sala informado está incorreto..
        /// </summary>
        public static string ErroCodigoSala {
            get {
                return ResourceManager.GetString("ErroCodigoSala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A data final está incorreta..
        /// </summary>
        public static string ErroDataFinal {
            get {
                return ResourceManager.GetString("ErroDataFinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A data de inicio está incorreta..
        /// </summary>
        public static string ErroDataInicio {
            get {
                return ResourceManager.GetString("ErroDataInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A data de inicio é maior do que a data final..
        /// </summary>
        public static string ErroDataInicioMaiorQueFinal {
            get {
                return ResourceManager.GetString("ErroDataInicioMaiorQueFinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a As reuniões devem ser agendadas apenas para os dias úteis..
        /// </summary>
        public static string ErroDiaUtil {
            get {
                return ResourceManager.GetString("ErroDiaUtil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Reuniões não podem durar mais que 8 horas.
        /// </summary>
        public static string ErroDuracao {
            get {
                return ResourceManager.GetString("ErroDuracao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a As reuniões devem ser agendadas com no máximo 40 dias de antecedência..
        /// </summary>
        public static string ErroMaximoQuarentaDiasAntecedencia {
            get {
                return ResourceManager.GetString("ErroMaximoQuarentaDiasAntecedencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a As reuniões devem ser agendadas com no mínimo 1 dia de antecedência..
        /// </summary>
        public static string ErroMinimoUmDiaAntecedencia {
            get {
                return ResourceManager.GetString("ErroMinimoUmDiaAntecedencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Verificador de computadores não pode ser nulo..
        /// </summary>
        public static string ErroPossuiComputador {
            get {
                return ResourceManager.GetString("ErroPossuiComputador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Verificador de internet não pode ser nulo..
        /// </summary>
        public static string ErroPossuiInternet {
            get {
                return ResourceManager.GetString("ErroPossuiInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Verificador de TV e webcam não podem ser nulo..
        /// </summary>
        public static string ErroPossuiTvWebcam {
            get {
                return ResourceManager.GetString("ErroPossuiTvWebcam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Quantidade de pessoas não pode ser nulo..
        /// </summary>
        public static string ErroQuantidadePessoas {
            get {
                return ResourceManager.GetString("ErroQuantidadePessoas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Quantidade de pessoas informado é insuficiente..
        /// </summary>
        public static string ErroQuantidadePessoasInsuficiente {
            get {
                return ResourceManager.GetString("ErroQuantidadePessoasInsuficiente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a As salas disponíveis acomodam no máximo 20 pessoas..
        /// </summary>
        public static string ErroQuantidadePessoasMaisQueSuficiente {
            get {
                return ResourceManager.GetString("ErroQuantidadePessoasMaisQueSuficiente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível reservar uma sala..
        /// </summary>
        public static string ErroSala {
            get {
                return ResourceManager.GetString("ErroSala", resourceCulture);
            }
        }
    }
}
